# nolint start
exports_details <- tibble::tribble(
  ~original_names,                                     ~labels,                                ~short_names,      ~categoria, ~nivel,                ~direct_parent,
  "1. Minerales",                                 "Minerales",                                 "minerales",     "minerales",      1,                            NA,
  "Oro",                                       "Oro",                                       "oro",     "minerales",      3,                   "Minerales",
  "Ferroníquel",                               "Ferroníquel",                               "ferroníquel",     "minerales",      3,                   "Minerales",
  "Cobre",                                     "Cobre",                                     "cobre",     "minerales",      3,                   "Minerales",
  "Plata",                                     "Plata",                                     "plata",     "minerales",      3,                   "Minerales",
  "Bauxita",                                   "Bauxita",                                   "bauxita",     "minerales",      3,                   "Minerales",
  "Piedra caliza",                             "Piedra caliza",                             "piedra_caliza",     "minerales",      3,                   "Minerales",
  "Zinc",                                      "Zinc",                                      "zinc",     "minerales",      3,                   "Minerales",
  "Otros minerales",                           "Otros minerales",                           "otros_minerales",     "minerales",      3,                   "Minerales",
  "2. Agropecuarios",                             "Agropecuarios",                             "agropecuarios", "agropecuarios",      1,                            NA,
  "2.1 Nacionales",                  "Agropecuarios Nacionales",                  "agropecuarios_nacionales", "agropecuarios",      2,               "Agropecuarios",
  "Guineos",                                   "Guineos",                                   "guineos", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Cacao en grano",                            "Cacao en grano",                            "cacao_en_grano_agro_nac", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Aguacates",                                 "Aguacates",                                 "aguacates", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Ajíes y pimientos",                         "Ajíes y pimientos",                         "ajíes_y_pimientos", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Cocos secos",                               "Cocos secos",                               "cocos_secos", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Café en grano",                             "Café en grano",                             "café_en_grano", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Batata",                                    "Batata",                                    "batata", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Plátanos",                                  "Plátanos",                                  "plátanos", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Tabaco en rama",                            "Tabaco en rama",                            "tabaco_en_rama", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "Otros agropecuarios",                       "Otros agropecuarios",                       "otros_agropecuarios", "agropecuarios",      3,    "Agropecuarios Nacionales",
  "2.2 Zonas Francas",               "Agropecuarios Zonas Francas",               "agropecuarios_zonas_francas", "agropecuarios",      2,               "Agropecuarios",
  "Cacao en grano",                            "Cacao en grano",                            "cacao_en_grano_agro_zf", "agropecuarios",      3, "Agropecuarios Zonas Francas",
  "Otros agropecuarios",                       "Otros agropecuarios",                      "otros_agropecuarios_", "agropecuarios",      3, "Agropecuarios Zonas Francas",
  "3. Industriales",                              "Industriales",                              "industriales",  "industriales",      1,                            NA,
  "3.1 Nacionales",                   "Industriales Nacionales",                   "industriales_nacionales",  "industriales",      2,                "Industriales",
  "Azúcar crudo y derivados",                  "Azúcar crudo y derivados",                  "azúcar_crudo_y_derivados",  "industriales",      3,     "Industriales Nacionales",
  "Productos de la industria química",         "Productos de la industria química",         "productos_de_la_industria_química",  "industriales",      3,     "Industriales Nacionales",
  "Cemento gris",                              "Cemento gris",                              "cemento_gris",  "industriales",      3,     "Industriales Nacionales",
  "Varillas de acero",                         "Varillas de acero",                         "varillas_de_acero",  "industriales",      3,     "Industriales Nacionales",
  "Ron de caña",                               "Ron de caña",                               "ron_de_caña",  "industriales",      3,     "Industriales Nacionales",
  "Envases y tapas plásticos",                 "Envases y tapas plásticos",                 "envases_y_tapas_plásticos",  "industriales",      3,     "Industriales Nacionales",
  "Harina de trigo",                           "Harina de trigo",                           "harina_de_trigo",  "industriales",      3,     "Industriales Nacionales",
  "Sazonadores y condimentos prep.",           "Sazonadores y condimentos prep.",           "sazonadores_y_condimentos_prep.",  "industriales",      3,     "Industriales Nacionales",
  "Galletas",                                  "Galletas",                                  "galletas",  "industriales",      3,     "Industriales Nacionales",
  "Cervezas",                                  "Cervezas",                                  "cervezas",  "industriales",      3,     "Industriales Nacionales",
  "Pastas alimenticias",                       "Pastas alimenticias",                       "pastas_alimenticias",  "industriales",      3,     "Industriales Nacionales",
  "Cajas de cartón corrugado",                 "Cajas de cartón corrugado",                 "cajas_de_cartón_corrugado",  "industriales",      3,     "Industriales Nacionales",
  "Frutas procesadas",                         "Frutas procesadas",                         "frutas_procesadas",  "industriales",      3,     "Industriales Nacionales",
  "Tabaco manufacturado",                      "Tabaco manufacturado",                      "tabaco_manufacturado",  "industriales",      3,     "Industriales Nacionales",
  "Café manufacturado",                        "Café manufacturado",                        "café_manufacturado",  "industriales",      3,     "Industriales Nacionales",
  "Cacao Manufacturado",                       "Cacao Manufacturado",                       "cacao_manufacturado_ind_nac",  "industriales",      3,     "Industriales Nacionales",
  "Aceite de soya",                            "Aceite de soya",                            "aceite_de_soya",  "industriales",      3,     "Industriales Nacionales",
  "Combustibles derivados del petróleo",       "Combustibles derivados del petróleo",       "combustibles_derivados_del_petróleo",  "industriales",      3,     "Industriales Nacionales",
  "Alimentos para aeronaves",                  "Alimentos para aeronaves",                  "alimentos_para_aeronaves_ind_nac",  "industriales",      3,     "Industriales Nacionales",
  "Combustibles para aeronaves",               "Combustibles para aeronaves",               "combustibles_para_aeronaves_ind_nac",  "industriales",      3,     "Industriales Nacionales",
  "Otros industriales",                        "Otros industriales",                        "otros_industriales_ind_nac",  "industriales",      3,     "Industriales Nacionales",
  "3.2 Zonas Francas",                "Industriales Zonas Francas",                "industriales_zonas_francas",  "industriales",      2,                "industriales",
  "Confecciones textiles",                     "Confecciones textiles",                     "confecciones_textiles",  "industriales",      3,  "Industriales Zonas Francas",
  "Productos eléctricos",                      "Productos eléctricos",                      "productos_eléctricos",  "industriales",      3,  "Industriales Zonas Francas",
  "Artículos de joyería y conexos",            "Artículos de joyería y conexos",            "artículos_de_joyería_y_conexos",  "industriales",      3,  "Industriales Zonas Francas",
  "Productos farmacéuticos",                   "Productos farmacéuticos",                   "productos_farmacéuticos",  "industriales",      3,  "Industriales Zonas Francas",
  "Fabricación equipos médicos y quirúrgicos", "Fabricación equipos médicos y quirúrgicos", "fabricación_equipos_médicos_y_quirúrgicos",  "industriales",      3,  "Industriales Zonas Francas",
  "Manufacturas de calzados",                  "Manufacturas de calzados",                  "manufacturas_de_calzados",  "industriales",      3,  "Industriales Zonas Francas",
  "Manufacturas de tabaco",                    "Manufacturas de tabaco",                    "manufacturas_de_tabaco",  "industriales",      3,  "Industriales Zonas Francas",
  "Cacao manufacturado",                       "Cacao manufacturado",                       "cacao_manufacturado_ind_zf",  "industriales",      3,  "Industriales Zonas Francas",
  "Alimentos para aeronaves",                  "Alimentos para aeronaves",                  "alimentos_para_aeronaves_ind_zf",  "industriales",      3,  "Industriales Zonas Francas",
  "Otros industriales",                        "Otros industriales",                        "otros_industriales_ind_zf",  "industriales",      3,  "Industriales Zonas Francas",
  "Total  ( 1+2+3 )",                                     "Total",                                     "total",         "total",      1,                            NA,
  "Nacionales",                                "Nacionales",                                "nacionales",         "total",      2,                       "Total",
  "Zonas Francas",                             "Zonas Francas",                             "zonas_francas",         "total",      2,                       "Total",
  "Bienes Adquiridos en Puerto",               "Bienes Adquiridos en Puerto",               "bienes_adquiridos_en_puerto",         "total",      2,                       "Total",
  "Combustibles para aeronaves",               "Combustibles para aeronaves",               "combustibles_para_aeronaves",         "total",      3, "Bienes Adquiridos en Puerto",
  "Alimentos para aeronaves",                  "Alimentos para aeronaves",                  "alimentos_para_aeronaves",         "total",      3, "Bienes Adquiridos en Puerto"
)

# nolint end
usethis::use_data(exports_details, overwrite = TRUE)
